language: go

go:
  - 1.7.3

install:
  - go get golang.org/x/crypto/bcrypt
  - go get github.com/go-sql-driver/mysql
  - go get github.com/gorilla/mux
  - go get github.com/dgrijalva/jwt-go
  - go get github.com/urfave/negroni
  - go get github.com/joho/godotenv
  - go get github.com/Sirupsen/logrus
  - go get github.com/meatballhat/negroni-logrus
  - go get gopkg.in/DATA-DOG/go-sqlmock.v1

script:
  - go test -v ./...